stages:
  pipeline:
    cmd: >
      python main.py
      --data_config config/data.yaml
      --database_config config/db.yaml
      --feature_config config/features.yaml
      --ml_config config/ml.yaml
      --search_space config/search_spaces.yaml

    deps:
      - main.py
      - pipelines/features_builder.py
      - pipelines/data_builder.py
      - pipelines/train_pipeline.py
      - pipelines/evaluation_pipeline.py
      - pipelines/prediction_builder.py

      - config/data.yaml
      - config/db.yaml
      - config/features.yaml
      - config/ml.yaml
      - config/search_spaces.yaml

    outs:
      - artifacts/features.parquet
      - artifacts/train_dataset.parquet
      - artifacts/test_dataset.parquet
      - artifacts/predictions.parquet
      - artifacts/shap_values.parquet
      - artifacts/shap_summary.png